To do items addition
Andromeda-Learning/vanilla-todo-app-DakoMumladze pull request #1
Opened 2020-03-03 14:23 UTC by DakoMumladze

Created functionality to add to do-s to the list

2020-03-03 15:42 UTC, Anzormumladze submitted a review, later dismissed

2020-03-03 15:56 UTC, shavidzet commented on index.html
> +    <input type="text" placeholder="add to do" class="main-input">
იმისათვის, რომ input ელემენტში enterმა იმუშაოს უნდა დავრაპო formში, ასევე type="submit" ფორმის საბმიტირებისთვისააა, ისე აზრი არ აქვს.

2020-03-03 15:56 UTC, shavidzet requested changes

2020-03-03 15:56 UTC, shavidzet commented on index.html
> +    <input type="text" placeholder="add to do" class="main-input">
იმისათვის, რომ input ელემენტში enterმა იმუშაოს უნდა დავრაპო formში, ასევე type="submit" ფორმის საბმიტირებისთვისააა, ისე აზრი არ აქვს.

2020-03-06 21:05 UTC, shavidzet submitted a review, later dismissed

2020-03-07 13:49 UTC, Anzormumladze submitted a review, later dismissed

2020-03-07 14:04 UTC, shavidzet approved these changes

2020-03-07 14:08 UTC, Anzormumladze approved these changes

2020-03-07 14:18 UTC, salolipartia approved these changes

2020-03-07 14:23 UTC, merged